# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js Package Covid Strings1
gamefiles=Covid Strings 1 background.JS, first round.JS,second round.JS ,championship game.JS, game code.JS
on: 
play canvas
release:
  covid strings game files
   question types: multiple choice,math problem,sentence
  build:Covid Strings 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: scoreboard in background, button to select user's team,reference link for user to answer multiple choice question, button for each multiple choice answer, answer box for math problems 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:  computer with background image of colors of the rainbow with quotes to represent strings 
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
